services:
  db:
    image: mysql:8.0
    container_name: expensetracker-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - expensetracker-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: shiva2929/expensetracker-backend:latest
    container_name: expensetracker-backend
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - expensetracker-net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: shiva2929/expensetracker-frontend:latest
    container_name: expensetracker-frontend
    ports:
      - "80:80"
    networks:
      - expensetracker-net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  expensetracker-net:
    driver: bridge
